name: flutter_date_time_range_picker
description: A customizable date & time range picker for Flutter, based on date_range_picker with enhancements.
version: 0.0.5
homepage: https://github.com/ajumalebrahim/date_time_range_picker
repository: https://github.com/ajumalebrahim/date_time_range_picker
issue_tracker: https://github.com/ajumalebrahim/date_time_range_picker/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
